apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: unit-job
  region: eu-central-1

managedNodeGroups:
- name: unit-spot
  instanceSelector:
    vCPUs: 1
    memory: "1"
    cpuArchitecture: x86_64
  spot: true
  labels: { spot: 'true' }
  minSize: 1
  maxSize: 5
  iam:
    withAddonPolicies:
      autoScaler: true
      imageBuilder: true